#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.angla.demo.model
  mapperLocations: classpath:mapper/*.xml


spring:
  mastersources:
  -   url: jdbc:mysql://master1:3306/angla?useUnicode=true&characterEncoding=utf8
      username: root
      password: angla
      driver-class-name: com.mysql.jdbc.Driver

  - url: jdbc:mysql://master2:3306/angla?useUnicode=true&characterEncoding=utf8
    username: root
    password: angla
    driver-class-name: com.mysql.jdbc.Driver

  slavesources:
  -   url: jdbc:mysql://slave1:3307/angla?useUnicode=true&characterEncoding=utf8
      username: root
      password: angla
      driver-class-name: com.mysql.jdbc.Driver

  -   url: jdbc:mysql://slave2:3308/angla?useUnicode=true&characterEncoding=utf8
      username: root
      password: angla
      driver-class-name: com.mysql.jdbc.Driver

#配置日志
logging:
  config: classpath:logback-boot.xml


server:
  port: 8080


