


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.angla.demo.model
  mapperLocations: classpath:mapper/*.xml


spring:
  mastersource:
    url: jdbc:mysql://62.234.116.161:3306/angla?useUnicode=true&characterEncoding=utf8
    username: root
    password: angla
    driver-class-name: com.mysql.jdbc.Driver

  slavesource1:
    url: jdbc:mysql://62.234.116.161:3307/angla?useUnicode=true&characterEncoding=utf8
    username: root
    password: angla
    driver-class-name: com.mysql.jdbc.Driver

  slavesource2:
    url: jdbc:mysql://62.234.116.161:3308/angla?useUnicode=true&characterEncoding=utf8
    username: root
    password: angla
    driver-class-name: com.mysql.jdbc.Driver

#配置日志
logging:
  config: classpath:logback-boot.xml


server:
  port: 8080


